### ISSUE TITLE
vlc.sock Connection refused

### ISSUE THREAD

**Issue by shaief** [paulmadore/vlctransc#1]
Thanks for creating this script!

I face the following issue, but can't figure out how to solve it:

```
socat[6734] E connect(5, AF=1 "/home/user/vlctransc/vlc.sock", 33): Connection refused
```

Any idea what causing it?

Thanks!

**Comment by paulmadore** [comment]
Hi, that sounds to me like the user you're trying to run the script under doesn't have access to that directory. Conversely, the script itself has perms set wrong. Check the permissions of the folder and the file and let me know if you still have problems.

**Comment by paulmadore** [comment]
Haven't heard back. Guessing you figured out the perms. Closing.
